name: Build lede

on:
  workflow_dispatch

jobs:
  build_lede:
    name: Build lede firmware
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt clean all
          sudo -E apt update
          sudo -E apt full-upgrade -y
          sudo -E apt autoremove --purge -y
          sudo -E apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pyelftools libpython3-dev qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev

      - name: Clone source code
        run: |
          git clone https://github.com/coolsnowwolf/lede.git

      - name: Update And Install feeds
        run: |
          cd lede
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Generate configuration file
        run: |
          cd lede
          wget https://raw.githubusercontent.com/anonymous-july/OpenWrt/main/lede-config -O .config
          make defconfig

      - name: Make download
        run: |
          cd lede
          make download -j8

      - name: Compile firmware
        run: |
          cd lede
          make -j$(nproc)

      - name: Deliver firmware
        uses: actions/upload-artifact@v3
        with:
          name: lede_firmware
          path: ./lede/bin/targets/
